[package]
name = "proseq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
clap = { version = "4.3.3", features = ["derive"] }
csv = "1.2.2"
flate2 = "1.0.26"
kiddo = "2.1.1"
ndarray = "0.15.6"
petgraph = "0.6.3"
rand = "0.8.5"
rayon = "1.7.0"
spade = "2.2.0"
thread_local = "1.1.7"
