[package]
name = "proseg"
version = "0.0.13"
edition = "2021"

[profile.release]
# lto = true
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow2 = { version = "0.17.4", features = ["io_csv", "io_parquet", "io_parquet_compression"] }
clap = { version = "4.3.3", features = ["derive"] }
csv = "1.2.2"
flate2 = "1.0.26"
geo = "0.26.0"
indicatif = "0.17.5"
itertools = "0.10.5"
kiddo = "2.1.1"
libm = "0.2.7"
ndarray = { version = "0.15.6", features = ["rayon"] }
petgraph = "0.6.3"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.7.0"
thread_local = "1.1.7"
